################### EmptyDir Example Manifest ###################
# Documentation: https://kubernetes.io/docs/concepts/storage/volumes/#emptydir
---
apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
  - name: produser
    image: busybox:1.28
    command: 
    - /bin/sh 
    - -c
    args:
    - |
      while true; do 
        echo "Data generaed at $(date)"" >> /shared-data/data.txt
        sleep 10
      done
    volumeMounts:
    - name: shared-volume # name of the volume
      mountPath: /shared-data # path inside the container
    resources:
      requests: # minimum resources required
        memory: "32Mi"
        cpu: "100m"
      limits: # maximum resources allowed
        memory: "64Mi"
        cpu: "200m"
  - name: consumer
    image: busybox:1.28
    command: 
    - /bin/sh 
    - -c
    - "tail -f /shared-data/data.txt"
    volumeMounts:
    - name: shared-volume # name of the volume
      mountPath: /shared-data # path inside the container
    resources:
      requests: # minimum resources required
        memory: "32Mi"
        cpu: "100m"
      limits: # maximum resources allowed
        memory: "64Mi"
        cpu: "200m"
  volumes:
  - name: shared-volume # name of the volume
    emptyDir: {} # no more parameters needed
#      medium: Memory # to use memory instead of tmpfs (Use with caution 
#                     # to avoid overflowing memory or exceeding the limit 
#                     # set by the container)
#      sizeLimit: 1Gi # maximum size of the volume  