######## Example of pod using Downward API with VOLUMES #########
# Documentation: https://kubernetes.io/docs/tasks/inject-data-application/downward-api-volume-expose-pod-information/
---
apiVersion: v1
kind: Pod
metadata:
  name: downwardapi-pod
  labels:
    app.kubernetes.io/name: downwardapi-pod
    app.kubernetes.io/instance: test
    app.kubernetes.io/version: v.0.0.1
  annotations:
    kubernetes.io/author: "John Doe <jd@me.com>"
spec:
  containers:
    - name: app
      image: busybox:1.28
      command: 
        - "/bin/sh"
        - "-c"
      args:
        - |
          echo "Pod name: $(cat /etc/podinfo/name)";
          echo "Pod namespace: $(cat /etc/podinfo/namespace)";
          echo "Pod labels: $(cat /etc/podinfo/labels)";
          echo "Pod annotations: $(cat /etc/podinfo/annotations)";
          echo "CPU limit: $(cat /etc/podinfo/cpu_limit)";
          echo "Memory limit: $(cat /etc/podinfo/memory_limit)";
          sleep infinity
      volumeMounts:
        - name: podinfo
          mountPath: /etc/podinfo
      restartPolicy: Never
  volumes:
    - name: podinfo
      downwardAPI:
        items:
        ## Pod metadata
        - path: "name"
          fieldRef:
            fieldPath: metadata.name
        - path: "namespace"
          fieldRef:
            fieldPath: metadata.namespace
        - path: "labels"
          fieldRef:
            fieldPath: metadata.labels
        - path: "annotations"
          fieldRef:
            fieldPath: metadata.annotations
        ## Container metadata
        - path: "cpu_limit"
          resourceFieldRef:
            containerName: app
            resource: limits.cpu
            divisor: "1"
        - path: "memory_limit"
          resourceFieldRef:
            containerName: app
            resource: limits.memory
            divisor: "1"