#### Example of manual creating PVC #########
# Documentation: https://kubernetes.io/docs/concepts/storage/persistent-volumes/#manual
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc-01
#  labels:
#    app.kubernetes.io/name: app-storage
#    app.kubernetes.io/instance: test
spec:
  # request for similar access modes
  accessModes:
    - ReadWriteMany
  # request for starage with size or bigger
  resources:
    requests:
      storage: 1Gi
  # request for PV with same labels
#  selector:
#    matchLabels:
#      app.kubernetes.io/instance: manual