##### PV&PVC Manifest #######
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-02
  labels:
    app.kubernetes.io/name: nfs-storsge
    app.kubernetes.io/instance: manual
spec:
  storageClassName: ""
  # storage size in a volume
  capacity:
    storage: 1Gi
  # volume type (who can r/w)
  accessModes:
    - ReadWriteMany #(could be list of modes)
  # what to do when volume is deleted
  persistentVolumeReclaimPolicy: Retain
  # storage type
  nfs:
    # nfs server ip addr
    server: 192.168.0.3
    # path in nfs server
    path: /data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc-02
  labels:
    app.kubernetes.io/name: app-storage
    app.kubernetes.io/instance: test
spec:
  storageClassName: ""
  # request for similar access modes
  accessModes:
    - ReadWriteMany
  # request for starage with size or bigger
  resources:
    requests:
      storage: 500Mi
  # request for PV with same labels
  selector:
    matchLabels:
      app.kubernetes.io/instance: manual
---
apiVersion: v1
kind: Pod
metadata:
  name: pv-and-pvc-pod
  labels:
    app.kubernetes.io/name: pv-and-pvc-pod
    app.kubernetes.io/instance: test
    app.kubernetes.io/version: v.0.0.1
spec:
  volumes:
    - name: storage
      persistentVolumeClaim:
        claimName: nfs-pvc-02
  containers:
    - name: app
      image: busybox:1.37
      command: # here we use sed to replace variables from config template to final config
        - "/bin/sh" 
        - "-c"
      args:
        - |
          while true; do
            echo "Logs: $(date)" >> /data/test.log;
            sleep 10;
          done
      volumeMounts:
        - name: storage
          mountPath: /data
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
        requests:
          memory: "64Mi"
          cpu: "250m"