---
apiVersion: v1
kind: Pod
metadata:
  name: pv-and-pvc-pod
  labels:
    app.kubernetes.io/name: pv-and-pvc-pod
    app.kubernetes.io/instance: test
    app.kubernetes.io/version: v.0.0.1
spec:
  volumes:
    - name: storage
      persistentVolumeClaim:
        claimName: nfs-pvc-03
  containers:
    - name: app
      image: busybox:1.37
      command: # here we use sed to replace variables from config template to final config
        - "/bin/sh" 
        - "-c"
        - "echo 'ok'"
        - sleep infinity
      #args:
      #  - |
      #    while true; do
      #      echo "Logs: $(date)" >> /data/test.log;
      #      sleep 10;
      #    done
      #volumeMounts:
      #  - name: storage
      #    mountPath: /data
      #resources:
      #  limits:
      #    memory: "128Mi"
      #    cpu: "500m"
      #  requests:
      #    memory: "64Mi"
      #    cpu: "250m"